### ISSUE TITLE
...RTMPHandler - Error connecting {}

### ISSUE THREAD

**Issue by ghost** [Yatko/video-chat#3]
Hello
I have successfully compiled the java and flash parts , to run on a red5 server .

No I have this error message:

[INFO] [RTMPConnectionExecutor#Z1JUJ1SUZHUTS-1] com.jabbercam.JabberCamApp - W3C x-category:session x-event:connect c-ip:90.86.159.41 c-client-id:0
[ERROR] [RTMPConnectionExecutor#Z1JUJ1SUZHUTS-1] org.red5.server.net.rtmp.RTMPHandler - Error connecting {}
java.lang.NullPointerException: null
        at com.jabbercam.JabberCamAppData.executeQuery(JabberCamAppData.java:63) ~[na:na]
        at com.jabbercam.JabberCamApp.appConnect(JabberCamApp.java:87) ~[na:na]
        at org.red5.server.adapter.MultiThreadedApplicationAdapter.connect(MultiThreadedApplicationAdapter.java:321) ~[red5-server.jar:1.0.4-RELEASE]
        at org.red5.server.adapter.ApplicationAdapter.connect(ApplicationAdapter.java:42) ~[red5-server.jar:1.0.4-RELEASE]
        at org.red5.server.scope.Scope.connect(Scope.java:255) ~[red5-server-common-1.0.4-RELEASE.jar:na]
        at org.red5.server.BaseConnection.connect(BaseConnection.java:354) ~[red5-server-common-1.0.4-RELEASE.jar:na]
        at org.red5.server.net.rtmp.RTMPConnection.connect(RTMPConnection.java:397) ~[red5-server-common-1.0.4-RELEASE.jar:1.0.4-RELEASE]
        at org.red5.server.net.rtmp.RTMPMinaConnection.connect(RTMPMinaConnection.java:87) ~[red5-server-common-1.0.4-RELEASE.jar:1.0.4-RELEASE]
        at org.red5.server.net.rtmp.RTMPHandler.onCommand(RTMPHandler.java:347) ~[red5-server-common-1.0.4-RELEASE.jar:1.0.4-RELEASE]
        at org.red5.server.net.rtmp.BaseRTMPHandler.messageReceived(BaseRTMPHandler.java:105) [red5-server-common-1.0.4-RELEASE.jar:1.0.4-RELEASE]
        at org.red5.server.net.rtmp.ReceivedMessageTask.call(ReceivedMessageTask.java:57) [red5-server-common-1.0.4-RELEASE.jar:1.0.4-RELEASE]
        at org.red5.server.net.rtmp.ReceivedMessageTask.call(ReceivedMessageTask.java:11) [red5-server-common-1.0.4-RELEASE.jar:1.0.4-RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
[WARN] [RTMPConnectionExecutor#Z1JUJ1SUZHUTS-1] org.red5.server.net.rtmp.RTMPConnManager - Connection not found for Z1JUJ1SUZHUTS

Same problem with red5 106release.

The error is in the SQL query execution section,
I ran the SQL request manually (unix shell) , it went just fine .

Best regards and thank you in advance .

**Comment by ghost** [comment]
problem solved .
